events {}

http {

    upstream stable {
        server app-blue:5000;
    }

    upstream canary {
        server app-green:5000;
    }

    split_clients "${http_x_canary_id}" $deployment_backend {
        0% stable;
        * canary;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://$deployment_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
